# This is a basic workflow to help you get started with Actions

name: Prerelease

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]') && !startsWith(github.event.head_commit.message, '[release]')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          # token: ${{ secrets.REPO_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16

      - run: yarn

      - name: Bump & build
        run: echo "Changes found" && npm version prerelease --no-git-tag-version && yarn build

      - uses: JS-DevTools/npm-publish@v1
        name: Publish
        with:
            token: ${{ secrets.NPM_TOKEN }}
            tag: dev
            access: public
            package: package.json

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          add: 'package.json'
          message: '[SKIP CI] Prerelease'
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
